# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.17 on 2020-05-23 13:04
=======
# Generated by Django 1.11 on 2020-01-29 16:15
>>>>>>> 12ab2afe0cb239a0b8f25d2d4c8f49784ec7dc6b
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('name', models.CharField(max_length=75, unique=True, validators=[django.core.validators.RegexValidator("^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\-)|(:)|(\\')]+$")])),
=======
                ('name', models.CharField(max_length=75, unique=True, validators=[django.core.validators.RegexValidator(b"^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\-)|(:)|(\\')]+$")])),
>>>>>>> 12ab2afe0cb239a0b8f25d2d4c8f49784ec7dc6b
                ('approved_status', models.IntegerField(default=1)),
            ],
        ),
    ]
